apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  namespace: python
  labels:
    app: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: videogameapi
          image: videogameapi
          ports:
            - name: http
              containerPort: 5050