apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: python
images:
- newName: silne30/
  newTag: a0b92d47cee681dcb0fb7f34beba0f3942e392c0
- name: videogameapi
  newName: silne30/videogameapi
  newTag: 4d196375d4fd0f9008fea67913a24f9a210cfc0a
