apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: python
images:
- name: videogameapi
  newName: silne30/videogameapi
  newTag: 2716abcd0cbe152ffb296a4589f6e431577a256d
