apiVersion: v1
kind: Service
metadata:
  name: python
  namespace: python
  labels:
    app: python
spec:
  type: LoadBalancer
  ports:
    - port: 5050
      targetPort: 5050
  selector:
    app: python