apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: python
  name: python
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: python
  name: python
  namespace: python
spec:
  ports:
  - port: 5050
    targetPort: 5050
  selector:
    app: python
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python
  name: python
  namespace: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - image: silne30/videogameapi:a5cea3fa86e67f2e0589300397198179d94f17e1
        name: videogameapi
        ports:
        - containerPort: 5050
          name: http
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
      nodeSelector:
        beta.kubernetes.io/os: linux
